sudo: required
services:
  - docker
before_install:
  - echo "Before Install"
install:
  - echo "Install"
before_script:
  - echo "Before Script"
script:
  - bash test.sh
after_success:
  - echo "Success"
after_failure:
  - echo "Error"
after_script:
  - echo "Success"